"""Provide backend-neutral Modbus connections, units, and shared types."""

from ._client import (
    BaseModbusConnection as ModbusConnection,
)
from ._client import (
    ModbusSerialParams,
    ModbusTcpParams,
    ModbusTlsParams,
    ModbusUdpParams,
)
from ._protocol import ModbusUnit
from ._types import WordOrder
from .exceptions import (
    AcknowledgeBlockReadError,
    AcknowledgeError,
    BlockReadError,
    ClientClosedError,
    ExceptionCode,
    GatewayPathUnavailableBlockReadError,
    GatewayPathUnavailableError,
    GatewayTargetBlockReadError,
    GatewayTargetError,
    IllegalDataAddressBlockReadError,
    IllegalDataAddressError,
    IllegalDataValueBlockReadError,
    IllegalDataValueError,
    IllegalFunctionBlockReadError,
    IllegalFunctionError,
    MemoryParityBlockReadError,
    MemoryParityError,
    ModbusConnectionError,
    ModbusError,
    ModbusExceptionError,
    ModbusProtocolError,
    ModbusTimeoutError,
    ServerDeviceBusyBlockReadError,
    ServerDeviceBusyError,
    ServerDeviceFailureBlockReadError,
    ServerDeviceFailureError,
)

__all__ = [
    "AcknowledgeBlockReadError",
    "GatewayPathUnavailableBlockReadError",
    "GatewayTargetBlockReadError",
    "IllegalDataAddressBlockReadError",
    "IllegalDataValueBlockReadError",
    "IllegalFunctionBlockReadError",
    "MemoryParityBlockReadError",
    "ServerDeviceBusyBlockReadError",
    "ServerDeviceFailureBlockReadError",
    "ServerDeviceFailureError",
    "ServerDeviceBusyError",
    "MemoryParityError",
    "IllegalFunctionError",
    "IllegalDataValueError",
    "IllegalDataAddressError",
    "GatewayTargetError",
    "GatewayPathUnavailableError",
    "ExceptionCode",
    "AcknowledgeError",
    "BlockReadError",
    "ClientClosedError",
    "ModbusConnection",
    "ModbusConnectionError",
    "ModbusError",
    "ModbusExceptionError",
    "ModbusProtocolError",
    "ModbusSerialParams",
    "ModbusTcpParams",
    "ModbusTimeoutError",
    "ModbusTlsParams",
    "ModbusUdpParams",
    "ModbusUnit",
    "WordOrder",
]
